/**
 * Seed data for Taraba State Portal
 * Contains initial data for schools, hospitals, and MDAs
 */

import { SchoolInsert } from "@/lib/supabase/schools";
import { HospitalInsert } from "@/lib/supabase/hospitals";
import { MDA } from "@/lib/data/mdas";

// ==================== SCHOOLS ====================

export const seedSchools: SchoolInsert[] = [
  // Universities (3)
  {
    name: "Federal University, Wukari",
    level: "Tertiary",
    ownership: "Public",
    lga: "Wukari",
    address: "Wukari, Taraba State",
    enrollment_male: 2500,
    enrollment_female: 2100,
    contact_phone: "0802 000 0000",
    contact_email: "info@fuwukari.edu.ng",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: true,
  },
  {
    name: "Taraba State University, Jalingo",
    level: "Tertiary",
    ownership: "Public",
    lga: "Jalingo",
    address: "Jalingo, Taraba State",
    enrollment_male: 3200,
    enrollment_female: 2800,
    contact_phone: "0802 000 0001",
    contact_email: "info@tsuniversity.edu.ng",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: true,
  },
  {
    name: "Kwararafa University, Wukari",
    level: "Tertiary",
    ownership: "Private",
    lga: "Wukari",
    address: "Wukari, Taraba State",
    enrollment_male: 800,
    enrollment_female: 700,
    contact_phone: "0802 000 0002",
    contact_email: "info@kwararafauniversity.edu.ng",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: true,
  },

  // Colleges (8)
  {
    name: "College of Education, Zing",
    level: "Tertiary",
    ownership: "Public",
    lga: "Zing",
    address: "Zing, Taraba State",
    enrollment_male: 1200,
    enrollment_female: 1100,
    contact_phone: "0802 000 0003",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: true,
  },
  {
    name: "Taraba State College of Agriculture, Jalingo",
    level: "Tertiary",
    ownership: "Public",
    lga: "Jalingo",
    address: "Jalingo, Taraba State",
    enrollment_male: 900,
    enrollment_female: 800,
    contact_phone: "0802 000 0004",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Taraba State College of Health Technology, Takum",
    level: "Tertiary",
    ownership: "Public",
    lga: "Takum",
    address: "Takum, Taraba State",
    enrollment_male: 600,
    enrollment_female: 700,
    contact_phone: "0802 000 0005",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Taraba State College of Nursing and Midwifery, Jalingo",
    level: "Tertiary",
    ownership: "Public",
    lga: "Jalingo",
    address: "Jalingo, Taraba State",
    enrollment_male: 200,
    enrollment_female: 800,
    contact_phone: "0802 000 0006",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Peacock College of Education, Jalingo",
    level: "Tertiary",
    ownership: "Private",
    lga: "Jalingo",
    address: "Jalingo, Taraba State",
    enrollment_male: 500,
    enrollment_female: 450,
    contact_phone: "0802 000 0007",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Muwanshat College of Health Science and Technology, Jalingo",
    level: "Tertiary",
    ownership: "Private",
    lga: "Jalingo",
    address: "Jalingo, Taraba State",
    enrollment_male: 400,
    enrollment_female: 500,
    contact_phone: "0802 000 0008",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "College of Health Sciences and Technology, Mutum Biyu",
    level: "Tertiary",
    ownership: "Public",
    lga: "Gassol",
    address: "Mutum Biyu, Taraba State",
    enrollment_male: 350,
    enrollment_female: 400,
    contact_phone: "0802 000 0009",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "De-Champions College of Health science and Technology, Lau",
    level: "Tertiary",
    ownership: "Private",
    lga: "Lau",
    address: "Lau, Taraba State",
    enrollment_male: 300,
    enrollment_female: 350,
    contact_phone: "0802 000 0010",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },

  // Polytechnics (2)
  {
    name: "Federal Polytechnic Bali",
    level: "Tertiary",
    ownership: "Public",
    lga: "Bali",
    address: "Bali, Taraba State",
    enrollment_male: 2800,
    enrollment_female: 2500,
    contact_phone: "0802 000 0011",
    contact_email: "info@fedpolybali.edu.ng",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: true,
  },
  {
    name: "Taraba State Polytechnic, Suntai",
    level: "Tertiary",
    ownership: "Public",
    lga: "Bali",
    address: "Suntai, Bali, Taraba State",
    enrollment_male: 2200,
    enrollment_female: 2000,
    contact_phone: "0802 000 0012",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: true,
  },

  // Secondary Schools (Sample - 12 key schools from the list)
  {
    name: "Government Day Senior Secondary School, Garba Chede",
    level: "Secondary",
    ownership: "Public",
    lga: "Bali",
    address: "Garba Chede, Bali, Taraba State",
    enrollment_male: 320,
    enrollment_female: 280,
    contact_phone: "0802 000 0013",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Government Day Senior Secondary School, Jen",
    level: "Secondary",
    ownership: "Public",
    lga: "Gashaka",
    address: "Jen, Taraba State",
    enrollment_male: 280,
    enrollment_female: 250,
    contact_phone: "0802 000 0014",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Government Day Technical Secondary School, Lankaviri",
    level: "Secondary",
    ownership: "Public",
    lga: "Gashaka",
    address: "Lankaviri, Taraba State",
    enrollment_male: 350,
    enrollment_female: 300,
    contact_phone: "0802 000 0015",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Government College Senior, Jalingo",
    level: "Secondary",
    ownership: "Public",
    lga: "Jalingo",
    address: "Hamaruna Way, Jalingo, Taraba State",
    enrollment_male: 450,
    enrollment_female: 400,
    contact_phone: "0802 000 0016",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: true,
  },
  {
    name: "Federal Government College, Wukari",
    level: "Secondary",
    ownership: "Public",
    lga: "Wukari",
    address: "Jalingo Road, Wukari, Taraba State",
    enrollment_male: 600,
    enrollment_female: 550,
    contact_phone: "0802 000 0017",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: true,
  },
  {
    name: "Federal Government Girls College, Jalingo",
    level: "Secondary",
    ownership: "Public",
    lga: "Jalingo",
    address: "FGGC Road, Jalingo, Taraba State",
    enrollment_male: 0,
    enrollment_female: 500,
    contact_phone: "0802 000 0018",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: true,
  },
  {
    name: "Government Science Senior Secondary School Nyabu Kaka, Jalingo",
    level: "Secondary",
    ownership: "Public",
    lga: "Jalingo",
    address: "Nyabu Kaka, Jalingo, Taraba State",
    enrollment_male: 380,
    enrollment_female: 320,
    contact_phone: "0802 000 0019",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Government Day Senior Secondary School, Zing Jamma",
    level: "Secondary",
    ownership: "Public",
    lga: "Zing",
    address: "Zing Jamma, Taraba State",
    enrollment_male: 300,
    enrollment_female: 280,
    contact_phone: "0802 000 0020",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Government Day Senior Secondary School, Lau",
    level: "Secondary",
    ownership: "Public",
    lga: "Lau",
    address: "Lau, Taraba State",
    enrollment_male: 250,
    enrollment_female: 230,
    contact_phone: "0802 000 0021",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Government Day Senior Secondary School, Donga",
    level: "Secondary",
    ownership: "Public",
    lga: "Donga",
    address: "Donga Rafin Kada Road, Donga, Taraba State",
    enrollment_male: 280,
    enrollment_female: 260,
    contact_phone: "0802 000 0022",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Government Day Senior Secondary School, Bali",
    level: "Secondary",
    ownership: "Public",
    lga: "Bali",
    address: "Bali, Taraba State",
    enrollment_male: 320,
    enrollment_female: 290,
    contact_phone: "0802 000 0023",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
  {
    name: "Government Secondary School Takum",
    level: "Secondary",
    ownership: "Public",
    lga: "Takum",
    address: "Ussa Road, Takum, Taraba State",
    enrollment_male: 400,
    enrollment_female: 350,
    contact_phone: "0802 000 0024",
    accreditation_status: "Accredited",
    status: "Accredited",
    boarding: false,
  },
];

// ==================== HOSPITALS ====================

export const seedHospitals: HospitalInsert[] = [
  {
    name: "Federal Medical Centre, Jalingo",
    level: "Specialist Hospital",
    ownership: "Public",
    lga: "Jalingo",
    address: "No. 1 Hospital Road, Jalingo, Taraba State",
    phone: "0805 667 8899",
    email: "info@fmcjalingo.gov.ng",
    bed_capacity: 350,
    icu_beds: 18,
    ambulance_count: 6,
    specialties: ["Emergency", "Maternity", "Surgery", "Dialysis", "Oncology"],
    status: "Operational",
    accreditation_status: "Accredited",
    last_inspection_date: "2024-08-12",
    next_inspection_date: "2025-02-15",
    notes: "New oncology wing commissioned Aug 2024.",
  },
  {
    name: "Takum General Hospital",
    level: "General Hospital",
    ownership: "Public",
    lga: "Takum",
    address: "Opp. Central Market, Takum, Taraba State",
    phone: "0803 441 2277",
    bed_capacity: 120,
    icu_beds: 4,
    ambulance_count: 2,
    specialties: ["Emergency", "Maternity", "Laboratory"],
    status: "Operational",
    accreditation_status: "Accredited",
    last_inspection_date: "2024-06-05",
    next_inspection_date: "2024-12-05",
    notes: "Lab equipment upgrade pending verification.",
  },
  {
    name: "Wukari General Hospital",
    level: "General Hospital",
    ownership: "Public",
    lga: "Wukari",
    address: "Wukari, Taraba State",
    phone: "0803 441 2278",
    bed_capacity: 100,
    icu_beds: 2,
    ambulance_count: 2,
    specialties: ["Emergency", "Maternity", "Pediatrics"],
    status: "Operational",
    accreditation_status: "Accredited",
    last_inspection_date: "2024-05-20",
    next_inspection_date: "2024-11-20",
  },
  {
    name: "Sacred Heart Mission Clinic",
    level: "Private Clinic",
    ownership: "Mission",
    lga: "Wukari",
    address: "No. 12 Mission Road, Wukari, Taraba State",
    phone: "0810 334 5566",
    email: "info@sacredheartclinic.org",
    bed_capacity: 45,
    icu_beds: 0,
    ambulance_count: 1,
    specialties: ["Maternity", "Immunization", "Antenatal"],
    status: "Operational",
    accreditation_status: "Accredited",
    last_inspection_date: "2024-03-28",
    next_inspection_date: "2024-09-28",
    notes: "Approved for expanded antenatal services.",
  },
  {
    name: "Royal Crest Medical Centre",
    level: "Private Clinic",
    ownership: "Private",
    lga: "Karim Lamido",
    address: "Plot 8 Medical Lane, Karim Lamido, Taraba State",
    phone: "0809 112 3344",
    email: "admin@royalcrestmedical.com",
    bed_capacity: 60,
    icu_beds: 2,
    ambulance_count: 1,
    specialties: ["Emergency", "Diagnostics", "Surgery"],
    status: "Operational",
    accreditation_status: "Accredited",
    last_inspection_date: "2024-09-01",
    next_inspection_date: "2025-03-01",
    notes: "Emergency unit completed.",
  },
  {
    name: "Gembu Primary Health Centre",
    level: "Primary Health Centre",
    ownership: "Public",
    lga: "Sardauna",
    address: "Gembu, Sardauna, Taraba State",
    phone: "0803 441 2279",
    bed_capacity: 30,
    icu_beds: 0,
    ambulance_count: 1,
    specialties: ["General Practice", "Immunization", "Maternity"],
    status: "Operational",
    accreditation_status: "Accredited",
    last_inspection_date: "2024-04-15",
    next_inspection_date: "2024-10-15",
  },
];

// ==================== MDAs ====================
// MDAs are already in lib/data/mdas.ts, we'll import and use them

export { mdas as seedMDAs } from "@/lib/data/mdas";

// ==================== SOCIAL PROGRAMS ====================

export interface SocialProgramSeed {
  name: string;
  code: string;
  description: string;
  is_active: boolean;
  requirements?: string;
  benefits?: string;
}

export const seedSocialPrograms: SocialProgramSeed[] = [
  {
    name: "Pension Scheme",
    code: "pension",
    description: "Monthly pension benefits for retired civil servants and eligible beneficiaries.",
    is_active: true,
    requirements: "Must be a retired civil servant with minimum 10 years of service. Valid retirement documents required.",
    benefits: "Monthly pension payments, healthcare benefits, and access to pensioner support programs.",
  },
  {
    name: "Disability Support",
    code: "disability",
    description: "Financial assistance and support services for persons living with disabilities.",
    is_active: true,
    requirements: "Valid disability certificate from recognized medical facility. Proof of residency in Taraba State.",
    benefits: "Monthly stipend, medical support, assistive devices, and vocational training opportunities.",
  },
  {
    name: "Widow Support Program",
    code: "widow",
    description: "Support program providing financial assistance and resources for widows in the state.",
    is_active: true,
    requirements: "Death certificate of spouse, proof of marriage, and residency in Taraba State.",
    benefits: "Monthly financial support, skills training, microfinance opportunities, and educational support for children.",
  },
  {
    name: "Youth Empowerment",
    code: "youth",
    description: "Skills development and entrepreneurship programs for young people aged 18-35.",
    is_active: true,
    requirements: "Age between 18-35 years, valid NIN, proof of residency, and educational qualifications (minimum SSCE).",
    benefits: "Skills training, startup capital, mentorship programs, and access to business development resources.",
  },
  {
    name: "Elderly Care Program",
    code: "elderly",
    description: "Comprehensive support program for senior citizens aged 65 and above.",
    is_active: true,
    requirements: "Age 65 years and above, valid identification, and proof of residency in Taraba State.",
    benefits: "Monthly stipend, free healthcare services, home care support, and social activities.",
  },
  {
    name: "Unemployment Benefits",
    code: "unemployment",
    description: "Temporary financial assistance for unemployed individuals actively seeking employment.",
    is_active: true,
    requirements: "Proof of unemployment, active job search, valid NIN, and residency in Taraba State.",
    benefits: "Monthly financial assistance, job placement services, and skills training programs.",
  },
  {
    name: "Maternal Health Support",
    code: "maternal",
    description: "Healthcare and financial support for expectant and nursing mothers.",
    is_active: true,
    requirements: "Pregnancy confirmation or birth certificate, valid identification, and residency in Taraba State.",
    benefits: "Free antenatal care, delivery support, postnatal care, and nutritional supplements.",
  },
  {
    name: "Orphan and Vulnerable Children Support",
    code: "orphan",
    description: "Educational and welfare support for orphaned and vulnerable children.",
    is_active: true,
    requirements: "Birth certificate, death certificate of parent(s), guardian documentation, and school enrollment.",
    benefits: "Educational support, monthly stipend, healthcare access, and psychosocial support.",
  },
];

